FROM ea31337/ea-tester
MAINTAINER kenorb
ARG OPT_TRACE
ENV OPT_TRACE $OPT_TRACE
ARG OPT_VERBOSE
ENV OPT_VERBOSE $OPT_VERBOSE
ARG TEST_EXPERT
ENV TEST_EXPERT $TEST_EXPERT
ENTRYPOINT ["/opt/scripts/run_backtest.sh"]
